/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupCompanyRouteImport } from './routes/setup-company'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppTrabalhosRouteImport } from './routes/app/trabalhos'
import { Route as AppOrcamentosRouteImport } from './routes/app/orcamentos'
import { Route as AppMateriaisRouteImport } from './routes/app/materiais'
import { Route as AppClientesRouteImport } from './routes/app/clientes'
import { Route as AppAReceberRouteImport } from './routes/app/a-receber'

const SetupCompanyRoute = SetupCompanyRouteImport.update({
  id: '/setup-company',
  path: '/setup-company',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTrabalhosRoute = AppTrabalhosRouteImport.update({
  id: '/trabalhos',
  path: '/trabalhos',
  getParentRoute: () => AppRoute,
} as any)
const AppOrcamentosRoute = AppOrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => AppRoute,
} as any)
const AppMateriaisRoute = AppMateriaisRouteImport.update({
  id: '/materiais',
  path: '/materiais',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppAReceberRoute = AppAReceberRouteImport.update({
  id: '/a-receber',
  path: '/a-receber',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/setup-company': typeof SetupCompanyRoute
  '/app/a-receber': typeof AppAReceberRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/materiais': typeof AppMateriaisRoute
  '/app/orcamentos': typeof AppOrcamentosRoute
  '/app/trabalhos': typeof AppTrabalhosRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/setup-company': typeof SetupCompanyRoute
  '/app/a-receber': typeof AppAReceberRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/materiais': typeof AppMateriaisRoute
  '/app/orcamentos': typeof AppOrcamentosRoute
  '/app/trabalhos': typeof AppTrabalhosRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/setup-company': typeof SetupCompanyRoute
  '/app/a-receber': typeof AppAReceberRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/materiais': typeof AppMateriaisRoute
  '/app/orcamentos': typeof AppOrcamentosRoute
  '/app/trabalhos': typeof AppTrabalhosRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/setup-company'
    | '/app/a-receber'
    | '/app/clientes'
    | '/app/materiais'
    | '/app/orcamentos'
    | '/app/trabalhos'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/setup-company'
    | '/app/a-receber'
    | '/app/clientes'
    | '/app/materiais'
    | '/app/orcamentos'
    | '/app/trabalhos'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/setup-company'
    | '/app/a-receber'
    | '/app/clientes'
    | '/app/materiais'
    | '/app/orcamentos'
    | '/app/trabalhos'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SetupCompanyRoute: typeof SetupCompanyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup-company': {
      id: '/setup-company'
      path: '/setup-company'
      fullPath: '/setup-company'
      preLoaderRoute: typeof SetupCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/trabalhos': {
      id: '/app/trabalhos'
      path: '/trabalhos'
      fullPath: '/app/trabalhos'
      preLoaderRoute: typeof AppTrabalhosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orcamentos': {
      id: '/app/orcamentos'
      path: '/orcamentos'
      fullPath: '/app/orcamentos'
      preLoaderRoute: typeof AppOrcamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/materiais': {
      id: '/app/materiais'
      path: '/materiais'
      fullPath: '/app/materiais'
      preLoaderRoute: typeof AppMateriaisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes': {
      id: '/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/a-receber': {
      id: '/app/a-receber'
      path: '/a-receber'
      fullPath: '/app/a-receber'
      preLoaderRoute: typeof AppAReceberRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAReceberRoute: typeof AppAReceberRoute
  AppClientesRoute: typeof AppClientesRoute
  AppMateriaisRoute: typeof AppMateriaisRoute
  AppOrcamentosRoute: typeof AppOrcamentosRoute
  AppTrabalhosRoute: typeof AppTrabalhosRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAReceberRoute: AppAReceberRoute,
  AppClientesRoute: AppClientesRoute,
  AppMateriaisRoute: AppMateriaisRoute,
  AppOrcamentosRoute: AppOrcamentosRoute,
  AppTrabalhosRoute: AppTrabalhosRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SetupCompanyRoute: SetupCompanyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
